# Dictionary of RSS feeds that we will fetch and combine
# GlobeNewsire / Europe - http://www.globenewswire.com/Rss/List
# Businesswire - Industries / https://www.businesswire.com/portal/site/home/news/industries/
# DowJones / WSJ / Markets - https://feeds.a.dj.com/rss/RSSMarketsMain.xml
# DowJones / Businesses - https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml
# SP Indices - https://us.spindices.com/rss/

# GlobeNewsire - company news
SRNE: http://www.globenewswire.com/RssFeed/Organization/64H6a0Nh8lTNEHeJMjgVEg==
AZO: http://www.globenewswire.com/RssFeed/Organization/TK10Ciu7R4HihWpK18_wbg==
SONO: https://www.globenewswire.com/RssFeed/Organization/xtWdMf21aNmRqVU-nlGttw==
V: https://www.globenewswire.com/RssFeed/Organization/Pww6jk7f-7sSKBTHNSrY6g==
WDAY: https://www.globenewswire.com/RssFeed/Organization/OJ2TZEIaOvRAW8iUU_BvMQ==
OUTR: https://www.globenewswire.com/RssFeed/Organization/gfG1UCfja6HrUx8AfFuTOw==
MMYT: https://www.globenewswire.com/RssFeed/Organization/oC3SoMkvzqq70-CVcc3wiA==
FDX: https://www.globenewswire.com/RssFeed/Organization/WHwn-U8B2POZUyCoRRT92g==
WINA: https://www.globenewswire.com/RssFeed/Organization/gFwRi4nFYSyYGt0lJU34GA==
POOL: https://www.globenewswire.com/RssFeed/Organization/1SO9hUBMz_ZnruAsM2PK9A==
UBNT: https://www.globenewswire.com/RssFeed/Organization/ycNVrkxdjfb3CMyfS5DyVg==
CSCO: https://www.globenewswire.com/RssFeed/Organization/vg-ifTo7dS30wvZBOdl3XQ==
HZO: https://www.globenewswire.com/RssFeed/Organization/9Qfwo0zxn9xMreNF04YC6A==
DFRG: https://www.globenewswire.com/RssFeed/Organization/MSNWRjVnGMe3VcLGX3ZYpA==
COST: https://www.globenewswire.com/RssFeed/Organization/v9LWUbm7yiThhZLa-wIVEg==
SJR: https://www.globenewswire.com/RssFeed/Organization/T7a9sVYHH3NvvMZ2iHrr_w==
PETM: https://www.globenewswire.com/RssFeed/Organization/tK47yVN1mE2UOBVq_MPTDA==
TOUR: https://www.globenewswire.com/RssFeed/Organization/LDocLtukilF69x_lw-ph7w==
GES: https://www.globenewswire.com/RssFeed/Organization/KfW0GQVXEWGHp8bmGHGzKg==
IMAX: https://www.globenewswire.com/RssFeed/Organization/JQdo8EPc5ttet53eDAc7dg==
LKQ: https://www.globenewswire.com/RssFeed/Organization/k6C2OgFK-tQdNFvZq_Xx6A==
WWW: https://www.globenewswire.com/RssFeed/Organization/eMrjDoF4dIMw-HFo6u-fhw==
CTRN: https://www.globenewswire.com/RssFeed/Organization/eMCunjNxml5HZJLv5gJ4MA==
NATH: https://www.globenewswire.com/RssFeed/Organization/Fg1CKoIDdcvt9IrrBcI2Gg==
KMX: https://www.globenewswire.com/RssFeed/Organization/vS3hvygcu97r_QXQe4MdRQ==
TWLO: https://www.globenewswire.com/RssFeed/Organization/1iBxGzo50QQ-KNQ3rIwOMA==
LB: https://www.globenewswire.com/RssFeed/Organization/54sEZ7vnHf8u3LiPbhI4Eg==
TSCO: https://www.globenewswire.com/RssFeed/Organization/Vgj50-7awk6OC-Ff9yvgRA==
ALGT: https://www.globenewswire.com/RssFeed/Organization/hO2sut2RxS0nvJOsM6KkKg==
FINL: https://www.globenewswire.com/RssFeed/Organization/_hjVmFQJ06wgREAepD9PVA==
TZOO: https://www.globenewswire.com/RssFeed/Organization/7hYGJz7VJ9SQYk5mtwFMDw==
FPAY: https://www.globenewswire.com/RssFeed/Organization/piymuao7c2T3YxJomJcB7w==
SAP: https://www.globenewswire.com/RssFeed/Organization/DdQXw-0-xPhBR8jg_b9OuQ==
IPIC: https://www.globenewswire.com/RssFeed/Organization/yWkJQv7Pz-ZqUUgT1Xa8uw==
TWMC: https://www.globenewswire.com/RssFeed/Organization/8aRGilqolhUsLz-TMuKHhg==
HTHT: https://www.globenewswire.com/RssFeed/Organization/5XEiDoAH_gb3IEfWezYDmg==
EVLV: https://www.globenewswire.com/RssFeed/Organization/pX9H5wlRNS3rjEngVmhe-g==
CDK: https://www.globenewswire.com/RssFeed/Organization/MXc1pj_yZXkdL1xmjkSr5g==
HIBB: https://www.globenewswire.com/RssFeed/Organization/zSP7EhJNf3Vh__Q_ii_65Q==
FTD: https://www.globenewswire.com/RssFeed/Organization/53dw1qKmKhyLliJEYSFxQg==
BJRI: https://www.globenewswire.com/RssFeed/Organization/bxRSRYb34OsKxao2ND7VjQ==
XSPA: https://www.globenewswire.com/RssFeed/Organization/qDy51RNN-mhM-WXb_Qv0MQ==
URBN: https://www.globenewswire.com/RssFeed/Organization/2DFwvyUfo9GC--9evC4Guw==
TXRH: https://www.globenewswire.com/RssFeed/Organization/JKLY9vNLdTdVjdPDS4DCqg==
FRAN: https://www.globenewswire.com/RssFeed/Organization/XXZaIM2yCrcrkkJRBIlDKA==
LTM: https://www.globenewswire.com/RssFeed/Organization/0wpF_eXdBgtKEkzjfmYijA==
SKUL: https://www.globenewswire.com/RssFeed/Organization/-auf5MlwE8RmQnxOgirbWQ==
VZ: https://www.globenewswire.com/RssFeed/Organization/VQaXCQzt-nE6EbhArH8A9A==
LQ: https://www.globenewswire.com/RssFeed/Organization/i8-Rij_oNdN8Jj-sW1fYvA==
FDS: https://www.globenewswire.com/RssFeed/Organization/StiDtrXh972aBwjryUyJWw==
DAVE: https://www.globenewswire.com/RssFeed/Organization/aO3zufXELBWQvb96bYXuxg==
HSNI: http://www.globenewswire.com/RssFeed/Organization/SBLQmVhNXyeffA_sDNbKAg==
FRSH: https://www.globenewswire.com/RssFeed/Organization/tPUa4INBij6dZ435z65Y2A==
SAVE: https://www.globenewswire.com/RssFeed/Organization/mQckLE_ByFKwCVMqiXS7rA==
PETS: https://www.globenewswire.com/RssFeed/Organization/PAmvHgAxcTUrp_0AJRvTjQ==
KONA: https://www.globenewswire.com/RssFeed/Organization/D3HhzrKUG3tQwIPllJkPsg==
TTWO: https://www.globenewswire.com/RssFeed/Organization/opV0hbL3Q7SBgFpiBAihNg==
LIVE: https://www.globenewswire.com/RssFeed/Organization/0Mrcm882X5Wn794Ex2wvKQ==
ETH: https://www.globenewswire.com/RssFeed/Organization/EU6nR75kZI4HLb4Qm-c5SA==
SHOS: https://www.globenewswire.com/RssFeed/Organization/7LRTmB5fIN5pOFhzqJlq-Q==
DAL: https://www.globenewswire.com/RssFeed/Organization/EzUjzeh-eSU_Dl4Uu_5V2Q==
JOUT: https://www.globenewswire.com/RssFeed/Organization/Gfw36fYzKjtgSJDA7qRKiQ==
JD: https://www.globenewswire.com/RssFeed/Organization/sFb2fLXHBOK2jLTp_YKf5Q==
ASNA: https://www.globenewswire.com/RssFeed/Organization/Ptan7NWH_xSVT_kDfiFqkQ==
PRSS: https://www.globenewswire.com/RssFeed/Organization/8cPuZgPZnSl5i7LzJsuJtg==
CARG: https://www.globenewswire.com/RssFeed/Organization/_o4mhzlj8-i4GDRzgGR6Xg==
BLMN: https://www.globenewswire.com/RssFeed/Organization/OOj8FGck3cK1ujDnYFfxjQ==
ROST: https://www.globenewswire.com/RssFeed/Organization/3gOUjJFoUI3hKxUIhj_prQ==
PBPB: https://www.globenewswire.com/RssFeed/Organization/DpFcpLkqfMYeRuYnw-hCSA==
GME: https://www.globenewswire.com/RssFeed/Organization/c2TgHxUrVaXMd0QFAaVeOA==
LZB: https://www.globenewswire.com/RssFeed/Organization/p_agoDe8EyChEhoeNEPtxg==
NROM: https://www.globenewswire.com/RssFeed/Organization/9cezea0d7IieUtTCGYpt9g==
true: https://www.globenewswire.com/RssFeed/Organization/C-hUER5xystzf94UHT_XLw==
YOGA: https://www.globenewswire.com/RssFeed/Organization/GJEso2Y-8lCHvuSIPiDGlQ==
CORE: https://www.globenewswire.com/RssFeed/Organization/_4yuaAwTDDEzQyk8G-5rbQ==
WEYS: https://www.globenewswire.com/RssFeed/Organization/5YeoTS3vqjK5AeMpaUB85A==
POST: https://www.globenewswire.com/RssFeed/Organization/gZ1PFHfg9NK9GZfUT3jiFA==
PLYA: https://www.globenewswire.com/RssFeed/Organization/a1HZVEl7AUTTXlGwkujNdA==
FOGO: https://www.globenewswire.com/RssFeed/Organization/MH8x5QdW0WXTl_WfA7o-SQ==
WIX: https://www.globenewswire.com/RssFeed/Organization/rtTO07L3o16nQ1iJIu_r-g==
T: https://www.globenewswire.com/RssFeed/Organization/0-qx6oYE4JdjaEze3cVrww==
RST: https://www.globenewswire.com/RssFeed/Organization/EwgKiPaEsf0c1eeTCOzULg==
BID: https://www.globenewswire.com/RssFeed/Organization/LoikBNg0hLebMFJZNfjJaw==
MYSZ: https://www.globenewswire.com/RssFeed/Organization/bGAoKk0lke6W126tBoNkZw==
IRGTQ: https://www.globenewswire.com/RssFeed/Organization/24qwyVrxp0RW09vz22p8Mw==
K: http://www.globenewswire.com/RssFeed/Organization/VdG_S8RA4C23pLq43Mu5Jg==
SHOO: https://www.globenewswire.com/RssFeed/Organization/aDiFGnNYJYTawF2pnPOYNQ==
BGFV: https://www.globenewswire.com/RssFeed/Organization/cUUulB5j37y5wd5aH2ILyQ==
SHOP: https://www.globenewswire.com/RssFeed/Organization/j5mLQ_1oEz5xNrOvAEPQTw==
PNRA: https://www.globenewswire.com/RssFeed/Organization/q6g2A10_ooWeYnw-LZ6HFQ==
OSTK: https://www.globenewswire.com/RssFeed/Organization/Oqz0DXsi-1fQQCcGaoDA1Q==
PAYC: https://www.globenewswire.com/RssFeed/Organization/JcWmPW5n11al3u47b2hs9A==
GE: https://www.globenewswire.com/RssFeed/Organization/rrqnZ_zwGCLrENVUWI__iQ==
ANGI: https://www.globenewswire.com/RssFeed/Organization/ntoQaq9PZxZYEMFj5vNPTQ==
TRIP: https://www.globenewswire.com/RssFeed/Organization/xHKYYGKr3xWdw7ezGaVI-A==
JIVE: http://www.globenewswire.com/RssFeed/Organization/RkId9l7aSUhC9Mi47QHPWg==
LWAY: https://www.globenewswire.com/RssFeed/Organization/rq7N-eqgPa0lejhE1Hnq2g==
DTEA: https://www.globenewswire.com/RssFeed/Organization/j8he00YE09OZoKfWn1bRJw==
TAST: http://www.globenewswire.com/RssFeed/Organization/2hc1Kld3nkTcLM47HjVScQ==
HOFT: https://www.globenewswire.com/RssFeed/Organization/lun_uxE6n2XlRtQ28bep2g==
AAL: https://www.globenewswire.com/RssFeed/Organization/C-kVMas2V_0EQCbeEDryvQ==
BBRG: https://www.globenewswire.com/RssFeed/Organization/7YNE2KmNmlzfRShR9xL4CA==
CHDN: https://www.globenewswire.com/RssFeed/Organization/sTPnPDp_lzYnlPEVJgAnGQ==
WORX: https://www.globenewswire.com/RssFeed/Organization/8Is36-3hGWx5ycxzIWWAgg==
COLM: https://www.globenewswire.com/RssFeed/Organization/yxT1apya5zxfh8dzVzle5w==
LBMH: https://www.globenewswire.com/RssFeed/Organization/hSOgR2xEvD_3Wx0bzL5_KA==
CTRP: https://www.globenewswire.com/RssFeed/Organization/5qsAX1eZExETbJz8EJKQmw==
CSTR: https://www.globenewswire.com/RssFeed/Organization/bJWeIGytUNt16WmvFfpU_Q==
SYMC: https://www.globenewswire.com/RssFeed/Organization/GimE1eG_gilbVm3NfnF__Q==
HPQ: https://www.globenewswire.com/RssFeed/Organization/3TUKK2Y0oP9g2iylr-j30g==
WEB: https://www.globenewswire.com/RssFeed/Organization/VDOPNz6JBH5jwc_gTVdLYQ==
SHAK: https://www.globenewswire.com/RssFeed/Organization/I8kmVwLAZS__6keCqKesVA==
LUV: https://www.globenewswire.com/RssFeed/Organization/eR0-2ECDgGzfZHygzxNIzA==
QUNR: https://www.globenewswire.com/RssFeed/Organization/diE4jBLsTXWKW56DxlMcpg==
HVT: https://www.globenewswire.com/RssFeed/Organization/gwnmCDrZwdwi3t9KznfgQg==
GIL: https://www.globenewswire.com/RssFeed/Organization/Qe-ClOSuFmVpl3tlaPcWjA==
WTW: https://www.globenewswire.com/RssFeed/Organization/2hQ08t37UzT9Bxj6Z9ZBmA==
NDLS: https://www.globenewswire.com/RssFeed/Organization/RknY9TiNRlqTfzLRzk0vPg==
NILE: https://www.globenewswire.com/RssFeed/Organization/6IEih98tMZZct5F2Dw_ojg==
TTS: https://www.globenewswire.com/RssFeed/Organization/H85ArQsLW5HaBiUXBRf9CA==
SENEA: https://www.globenewswire.com/RssFeed/Organization/wYpfN3e8UcZE-Os4unFUIg==
MSG: https://www.globenewswire.com/RssFeed/Organization/EXHe9LZ-RbMR7EWoUBfkag==
CMPR: https://www.globenewswire.com/RssFeed/Organization/4q6lyoWBW5PRqtwFAgbKGQ==
Z: https://www.globenewswire.com/RssFeed/Organization/8ET0L12UdFWOcLcL_2u_HA==
BSET: https://www.globenewswire.com/RssFeed/Organization/fdWZ8zwJUloTp3iB2IK_yw==
VRA: https://www.globenewswire.com/RssFeed/Organization/QQz2UnoHRzbRRPIgHSTplA==
FLO: https://www.globenewswire.com/RssFeed/Organization/tVyiZH48y1Vk_oFk5ytmkQ==
BURL: https://www.globenewswire.com/RssFeed/Organization/OGa_i0eLMMSOhR6AbML-aA==
FLWS: https://www.globenewswire.com/RssFeed/Organization/m20DlNFG13dJ44pP7XUK2w==
PLNT: https://www.globenewswire.com/RssFeed/Organization/PGEk7UPsJDiHcSl4hn6elA==
CTHR: https://www.globenewswire.com/RssFeed/Organization/8j-8plwrfClD0f0olDGlPA==
SKIS: https://www.globenewswire.com/RssFeed/Organization/jDKCLZI9Qq-VWERi0aPIuA==
LEG: https://www.globenewswire.com/RssFeed/Organization/HPgkaPm0DUg3mO6NgxaNAA==
MNRO: https://www.globenewswire.com/RssFeed/Organization/cWB0xawOkwdv8hVgxQiCqw==
HA: https://www.globenewswire.com/RssFeed/Organization/acDERePu_K80AuiRpR8i7w==
ANF: https://www.globenewswire.com/RssFeed/Organization/VUQSq3Noc4PYFcdP3WZdIA==
FOSL: https://www.globenewswire.com/RssFeed/Organization/1BuJ35rxXl6ir7o9oyIXMw==
SGC: https://www.globenewswire.com/RssFeed/Organization/vv6QAAHqVrcvjrrlgBFtzA==
FCAU: https://www.globenewswire.com/RssFeed/Organization/WOOxNgNg7AT7izwdaL3jcQ==
SPWH: https://www.globenewswire.com/RssFeed/Organization/RH3B-7Gh42aDEAMbzGafDA==
CRTO: http://www.globenewswire.com/RssFeed/Organization/_5mWAYggiUukqnZqsWcSMg==
MAR: https://www.globenewswire.com/RssFeed/Organization/MTarkY_npX4hp0OGN5BK5A==
DXLG: https://www.globenewswire.com/RssFeed/Organization/ClX6KfwRrBnWUEgqtpphJQ==
RP: https://www.globenewswire.com/RssFeed/Organization/gVX6lob3SVgnZ7efmD94Ig==
DXYN: https://www.globenewswire.com/RssFeed/Organization/5V-CZ3hIEOupm7IJiYzD8w==
CONN: https://www.globenewswire.com/RssFeed/Organization/d25--wrRu1lrxdWFDUfEQw==
DISH: https://www.globenewswire.com/RssFeed/Organization/9BA7wL9G7JouAsrf_mvWOw==
XPO: https://www.globenewswire.com/RssFeed/Organization/X8a487A1U5UqSjPIVOSjlw==
YNDX: https://www.globenewswire.com/RssFeed/Organization/zSBeDvkaBfkPo15jHfLOVw==
ADP: http://www.globenewswire.com/RssFeed/Organization/K_IVeYC67xrQU-AFILLb1w==
HABT: https://www.globenewswire.com/RssFeed/Organization/9Gbd1oJ3f0DVfAjkCWWmJQ==
PRTS: http://www.globenewswire.com/RssFeed/Organization/r0FIJAnJpU9GyGyrfWwvGQ==
JJSF: https://www.globenewswire.com/RssFeed/Organization/68tC3Kpw9VNP7TLg1tETJw==
ALRM: https://www.globenewswire.com/RssFeed/Organization/vIgyojyQo6wgcW1E4WXD8A==
OXM: https://www.globenewswire.com/RssFeed/Organization/OiedJq7XZunTite639H0DQ==
MIK: https://www.globenewswire.com/RssFeed/Organization/RG3Al2bI7L69pQobBy-n0w==
AMCX: https://www.globenewswire.com/RssFeed/Organization/H13XRZig38hIGVOz7GaFdA==
CBRL: https://www.globenewswire.com/RssFeed/Organization/KbbMne0t_bse_skbbatGmA==
JAX: https://www.globenewswire.com/RssFeed/Organization/Dkc6lGUYtwmLpbesl7LGEg==
GNUS: https://www.globenewswire.com/RssFeed/Organization/IR7MsKaRedcVM6FPQ0rJvA==
BWLD: https://www.globenewswire.com/RssFeed/Organization/1GlWfe2Du34EpxyjxLGbRw==
HOG: https://www.globenewswire.com/RssFeed/Organization/F4KnfrfofpXNO86ZT2n_Gw==
CHUY: https://www.globenewswire.com/RssFeed/Organization/jkiiN-7b6nVmkkcZrl9wpQ==
CAR: https://www.globenewswire.com/RssFeed/Organization/KFPr3usRCNN6GMFmB6Jj-Q==
KOSS: https://www.globenewswire.com/RssFeed/Organization/O1nwOgNEroEQ790L--1WUg==
RCII: https://www.globenewswire.com/RssFeed/Organization/-xBmYR3nmrOda5DEhtrtWw==
FOXA: https://www.globenewswire.com/RssFeed/Organization/FpDb8x9qPISIeqBT86SVaQ==
SMPL: https://www.globenewswire.com/RssFeed/Organization/kLcREY3XQew5KkWvr9GdrA==
GIII: https://www.globenewswire.com/RssFeed/Organization/i8alBdbA6gDaUH95xBWyBg==
EFX: https://www.globenewswire.com/RssFeed/Organization/FTbZjPBYAcF3Kl0ltmLe9g==
SP: https://www.globenewswire.com/RssFeed/Organization/OkVHiI2jGLPr8obByDOKiw==
TMUS: https://www.globenewswire.com/RssFeed/Organization/ppPTLB5V4Vt3nJFbOHFfcQ==
WING: https://www.globenewswire.com/RssFeed/Organization/nmfU3Nfh5OJsoMRbAeyFgQ==
PLCE: https://www.globenewswire.com/RssFeed/Organization/YBdfPF0IboSfBKRahYvRBA==
JMEI: https://www.globenewswire.com/RssFeed/Organization/U3vKk5p_izemxmePHB77sQ==
PF: https://www.globenewswire.com/RssFeed/Organization/-U6XJxny8FqWmMChfE1gQg==
OLLI: https://www.globenewswire.com/RssFeed/Organization/Kg204RZGyF99xXy9WSYZ1g==
UPS: https://www.globenewswire.com/RssFeed/Organization/6oAT-0gvUcQhwd4DozpKBw==
CBK: http://www.globenewswire.com/RssFeed/Organization/tu61s2TC1GB643COivPu7A==
MGPI: https://www.globenewswire.com/RssFeed/Organization/nTq-mIMly5Yg12bqdECRsw==
SMRT: https://www.globenewswire.com/RssFeed/Organization/OezlCXvVv09srPpwqxmGsg==
SCOR: https://www.globenewswire.com/RssFeed/Organization/EpEgHy1VptWlzrNukZzAQg==
CVEO: https://www.globenewswire.com/RssFeed/Organization/Ur0b0q4q1nCky8mEyPxzKQ==
LOGM: https://www.globenewswire.com/RssFeed/Organization/QSPlkB4DAacFHpq8Vpb0Bw==
LOCO: https://www.globenewswire.com/RssFeed/Organization/UXiUs-rQJSMRmJdlkKZyCQ==
JMBA: https://www.globenewswire.com/RssFeed/Organization/T43iZnxspkYP45-OG1ToVg==
JBLU: https://rss.globenewswire.com/RssFeed/Organization/LinrfhVZ4krbKQQOveePNQ==
ORLY: https://www.globenewswire.com/RssFeed/Organization/5Uh8fwAePMt8C1V1jTLNiA==
MUSA: https://www.globenewswire.com/RssFeed/Organization/mBdkPdQN0mT61AC2MK3t2A==
PZZA: https://www.globenewswire.com/RssFeed/Organization/hKnya4fMXzpQ9RswnjDIiQ==
SODA: https://www.globenewswire.com/RssFeed/Organization/c4jKXf7G7VeTItyAy9UImg==
SKYW: https://www.globenewswire.com/RssFeed/Organization/OZiGJi4f7UOv_D9i5VkDsw==
TACO: https://www.globenewswire.com/RssFeed/Organization/uc4BZgzhpxtn6f-7UOKkyg==
LE: https://www.globenewswire.com/RssFeed/Organization/ETYrbGm2gy375imAedP_dA==
PNK: https://www.globenewswire.com/RssFeed/Organization/pPPSbQqcxychrmlOnnLlGg==
SFIX: https://www.globenewswire.com/RssFeed/Organization/Iu_xLp0W3iAV0-h657tv2A==
DLTH: https://www.globenewswire.com/RssFeed/Organization/uu9DvXEAUXmcOJH-DF_IeQ==
CROX: https://www.globenewswire.com/RssFeed/Organization/0H3jtgzb7ghT8JGCPl0vNA==
MYCC: https://www.globenewswire.com/RssFeed/Organization/bGsTW-zx-Hj2oZPcHA_QTg==
ICON: https://www.globenewswire.com/RssFeed/Organization/bGsTW-zx-Hj2oZPcHA_QTg==
QSR: https://www.globenewswire.com/RssFeed/Organization/25IiXRlCgDXRfK8o9WBrMQ==
OKTA: http://www.globenewswire.com/RssFeed/Organization/-gRMRAzvPw7wlvq7tk5v6A==
MLCO: https://www.globenewswire.com/RssFeed/Organization/2gm4Q63KU_4g9U7JKNDxqw==
TRK: https://www.globenewswire.com/RssFeed/Organization/AmQ2bFbWbzfuayaGEWwi9Q==
TUES: https://www.globenewswire.com/RssFeed/Organization/OdeDDCFj2A9vgIUlnPjQEg==
CRMT: https://www.globenewswire.com/RssFeed/Organization/Sa-OL42GSPrHRCy2j8rZ_A==
MELI: https://www.globenewswire.com/RssFeed/Organization/s1R0l7zvxXiOd0FAGd0amw==
CATM: https://www.globenewswire.com/RssFeed/Organization/G-W_KVkbHCIHBOQjlrqEjA==
GNC: https://www.globenewswire.com/RssFeed/Organization/-j8VmPW4sqITtZh01VgJaQ==
DLA: https://www.globenewswire.com/RssFeed/Organization/Y6Y4YCTroLKbfigOcUE_UA==
GAIA: https://www.globenewswire.com/RssFeed/Organization/8mLuB8njR9ray6B_rHrlxQ==
NAKD: https://www.globenewswire.com/RssFeed/Organization/CiG0iP6XFqJqOH7KKXCGEg==
IFMK: https://www.globenewswire.com/RssFeed/Organization/4oG6IoNPNxTo_cRM1NyAeA==
FIVE: https://www.globenewswire.com/RssFeed/Organization/PYPQBGhe-PN7IH9jW9hs9A==
NCLH: https://www.globenewswire.com/RssFeed/Organization/lQAN-Dab5jV3K8Demgxo_A==
PERY: https://www.globenewswire.com/RssFeed/Organization/E6T8-Hd3dsC2lBZnRngMhw==
PRTY: https://www.globenewswire.com/RssFeed/Organization/HV40nD7foK6OT7hWwQmCIg==
MCRI: https://www.globenewswire.com/RssFeed/Organization/E0ewz0ElWFxOdX8xO46WCA==
C: https://www.globenewswire.com/RssFeed/Organization/0-BAhPA078fLwZWMcMoGPA==
LKII: https://www.globenewswire.com/RssFeed/Organization/LDusT4gqFdFUEcLGAEfAoQ==
PLAY: https://www.globenewswire.com/RssFeed/Organization/gKj0GaOmp8C4SIdQ21m6EQ==
RRGB: http://www.globenewswire.com/RssFeed/Organization/PYNzBfubDmZoaoOXFlnGVQ==
TSLA: https://www.globenewswire.com/RssFeed/Organization/DReN4SHIWoVofKIItDPneQ==
BOJA: https://www.globenewswire.com/RssFeed/Organization/vlMa-sG4f1l4C8F8cjQOVw==
ERBB: https://www.globenewswire.com/RssFeed/Organization/VMxZBFprPbTsUwzN93fNOA==
STAY: https://www.globenewswire.com/RssFeed/Organization/Rt3DoCl2GFtU86yrYQNRRw==
EZPW: https://www.globenewswire.com/RssFeed/Organization/Bwt2mCiGUjucoHDsf3DUwQ==
RT: https://www.globenewswire.com/RssFeed/Organization/US-KuGy80GMkHirNZROW2g==
CDLX: https://www.globenewswire.com/RssFeed/Organization/8SLs9givMEjeY-YQJdVoxA==
NXST: https://www.globenewswire.com/RssFeed/Organization/WFG2CW2H-oU3DGpN2iN2SA==
DENN: https://www.globenewswire.com/RssFeed/Organization/5t-sObttjVUswPuLIuUxaw==
FCFS: https://www.globenewswire.com/RssFeed/Organization/Iv3jUfgEOhLEnovcCPnCxw==